name: Luminous Counselling Services
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1370b3'
    - '#4f79cf'
    - '#d1d5fd'
    - '#97b1de'
    - '#0a3353'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
